### ISSUE TITLE
skip questions

### ISSUE THREAD

**Issue by mainex** [an-tonic/CO1111-Shared-Project#15]

**Comment by mainex** [comment]
нельзя скипнуть некоторые вопросы, хотя кнопка есть. например, вопрос про деревья у уника не скипается

**Comment by mainex** [comment]
![Image](https://user-images.githubusercontent.com/44476951/222656811-d3f5634b-8477-4b7c-83d9-fbf04652292e.png)

**Comment by an-tonic** [comment]
Issue closed. The bug is fixed
